version: "3.8"
services:
  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./Server/.env

  frontend:
    build:
      context: ./FCG_front-end
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./FCG_front-end/.env
    depends_on:
    - backend