const GAME_DELAY_ENUM = {
    // CONFIG ASSOCIATE WITH BACKEND
    TRICK_FINISHED_IN_SEC: 4,
    AFTER_LAST_CARD: 1,
    ROUND_FINISHED_IN_SEC: 4,
    SUMMARY_SCORE_IN_SEC: 5,
    FRIEND_APPEAR_IN_SEC: 2,

    // CONFIG ASSOCIATE WITH BACKEND
    AUCTION_IN_SEC: 10,
    SELECT_MAIN_CARD_IN_SEC: 30,
    PLAY_CARD_IN_SEC: 30,

}
export default GAME_DELAY_ENUM